apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-d
  description: Team D
spec:
  type: team
  profile:
    displayName: Team D
    email: team-d@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Bailey&backgroundType=gradientLinear&backgroundColor=b6e3f4,ffd5dc,ffdfbf,c0aede
  parent: boxoffice
  children: []
