apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
  description: Team B
spec:
  type: team
  profile:
    displayName: Team B
    email: team-b@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Abby&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  parent: backstage
  children: []
